### ISSUE TITLE
yu got termed? cuz you are offline at an unusual time

### ISSUE THREAD

**Issue by fininimini** [Callumgm/Cookies-Services-Website#3]
also how do i conver a "true" to an False and a "false" to an True

**Comment by fininimini** [comment]
bruuh anything else i kinda don use twiter

**Comment by fininimini** [comment]
Add me back on tikot. We can talk there. My name is fini_fpv

**Comment by Callumgm** [comment]
yeah i don't use it either but its impossible to get banned there and everyone messaging me there anyways
